apiVersion: images.banzaicloud.io/v1alpha1
kind: ImagePullSecret
metadata:
  name: acr-secrets
spec:
  registry:
    credentials:
      - name: acr-secrets
        namespace: {{ .Release.Namespace }}
  target:
    namespacesWithPods:
      annotations:
        - matchAnnotations:
            beezlabs.app/developer: first-party
    secret:
      name: acr-image-pull-secret
