{{- if .Values.clusterIssuer.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: api-token-secret
  namespace: {{ .Release.Namespace }}
stringData:
  api-token: {{ .Values.clusterIssuer.apiToken }}
{{- end -}}