{{- if .Values.clusterIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-secret
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.clusterIssuer.email }}
          apiTokenSecretRef:
            name: api-token-secret
            key: api-token
{{- end -}}